Minor edits for clean compile
BytesRobotics/ros2_t260 pull request #10
Opened 2020-07-31 15:33 UTC by bobgates

I've also put a bad PR in for the same things against the release branch. Still learning how to do PRs properly.

I've added dependency to image_transport and included a header that was required for a clean compile.

2020-08-01 21:51 UTC, Michael-Equi commented
@bobgates Could you go ahead and merge with the new code that I just pushed and get your PR passing the travis build?

2020-08-06 16:55 UTC, Michael-Equi requested changes
Looks good just go ahead and fix that merge artifact

2020-08-06 16:55 UTC, Michael-Equi commented on src/t260.cpp
> +=======
Please remove the merge artifacts

2020-08-07 08:06 UTC, bobgates reviewed
Merge artefact removed

2020-08-07 18:20 UTC, Michael-Equi approved these changes
Looks good. Thank you for your contribution.

2020-08-07 18:20 UTC, merged